# Generated by Django 4.0.5 on 2024-07-09 06:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CampusAVS',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('campusOrSchoolAcronym', models.CharField(max_length=50, unique=True)),
                ('campusName', models.TextField()),
                ('about', models.TextField()),
                ('flyer', models.ImageField(blank=True, upload_to='')),
                ('bibleStudyTime', models.CharField(blank=True, max_length=50)),
                ('bibleStudyVenue', models.TextField(blank=True)),
                ('fellowshipTime', models.CharField(blank=True, max_length=50)),
                ('fellowshipVenue', models.TextField(blank=True)),
                ('OtherScheduleOfServiceDetails', models.TextField(blank=True)),
                ('averageNumberOfStudent', models.PositiveIntegerField(blank=True, default=0, null=True)),
                ('numberOfWorkforce', models.PositiveIntegerField(blank=True, default=0, null=True)),
                ('joinAlumiGroup', models.URLField(blank=True, null=True)),
                ('posted', models.DateTimeField(auto_now_add=True)),
                ('last_edited', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'CampusAVS',
            },
        ),
        migrations.CreateModel(
            name='Secretary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=300)),
                ('picture', models.ImageField(blank=True, upload_to=None)),
                ('course', models.CharField(max_length=800)),
                ('level', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254)),
                ('phonenumber', models.CharField(max_length=50)),
                ('campusAcronym', models.CharField(max_length=50)),
                ('campus_by_admin', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='CentralApp.campusavs')),
            ],
        ),
        migrations.CreateModel(
            name='Coordinator',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=300)),
                ('picture', models.ImageField(blank=True, upload_to=None)),
                ('course', models.CharField(max_length=800)),
                ('level', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254)),
                ('phonenumber', models.CharField(max_length=50)),
                ('campusAcronym', models.CharField(max_length=50)),
                ('campus_by_admin', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='CentralApp.campusavs')),
            ],
        ),
    ]
