# Generated by Django 4.0.5 on 2024-07-09 19:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CentralApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='campusavs',
            name='coord_course',
            field=models.CharField(blank=True, max_length=800, null=True),
        ),
        migrations.AddField(
            model_name='campusavs',
            name='coord_email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='campusavs',
            name='coord_level',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='campusavs',
            name='coord_name',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='campusavs',
            name='coord_phonenumber',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='campusavs',
            name='coord_picture',
            field=models.ImageField(blank=True, upload_to=None),
        ),
        migrations.AddField(
            model_name='campusavs',
            name='secre_course',
            field=models.CharField(blank=True, max_length=800, null=True),
        ),
        migrations.AddField(
            model_name='campusavs',
            name='secre_email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='campusavs',
            name='secre_level',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='campusavs',
            name='secre_name',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='campusavs',
            name='secre_phonenumber',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='campusavs',
            name='secre_picture',
            field=models.ImageField(blank=True, upload_to=None),
        ),
    ]
