# Generated by Django 4.0.5 on 2024-07-09 19:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('CentralApp', '0002_campusavs_coord_course_campusavs_coord_email_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='campusavs',
            old_name='coord_course',
            new_name='coordinator_course',
        ),
        migrations.RenameField(
            model_name='campusavs',
            old_name='coord_email',
            new_name='coordinator_email',
        ),
        migrations.RenameField(
            model_name='campusavs',
            old_name='coord_level',
            new_name='coordinator_level',
        ),
        migrations.RenameField(
            model_name='campusavs',
            old_name='coord_name',
            new_name='coordinator_name',
        ),
        migrations.RenameField(
            model_name='campusavs',
            old_name='coord_phonenumber',
            new_name='coordinator_phonenumber',
        ),
        migrations.RenameField(
            model_name='campusavs',
            old_name='coord_picture',
            new_name='coordinator_picture',
        ),
        migrations.RenameField(
            model_name='campusavs',
            old_name='secre_course',
            new_name='secretary_course',
        ),
        migrations.RenameField(
            model_name='campusavs',
            old_name='secre_email',
            new_name='secretary_email',
        ),
        migrations.RenameField(
            model_name='campusavs',
            old_name='secre_level',
            new_name='secretary_level',
        ),
        migrations.RenameField(
            model_name='campusavs',
            old_name='secre_name',
            new_name='secretary_name',
        ),
        migrations.RenameField(
            model_name='campusavs',
            old_name='secre_phonenumber',
            new_name='secretary_phonenumber',
        ),
        migrations.RenameField(
            model_name='campusavs',
            old_name='secre_picture',
            new_name='secretary_picture',
        ),
    ]
