# Generated by Django 4.0.5 on 2024-07-10 02:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CentralApp', '0003_rename_coord_course_campusavs_coordinator_course_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='campusavs',
            name='campusOrSchoolAcronym',
            field=models.CharField(max_length=50),
        ),
    ]
