# Generated by Django 4.0.5 on 2024-07-10 05:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CentralApp', '0006_campusavsreport'),
    ]

    operations = [
        migrations.RenameField(
            model_name='campusavsreport',
            old_name='program',
            new_name='program_type',
        ),
        migrations.AddField(
            model_name='campusavsreport',
            name='year',
            field=models.CharField(default='2021', max_length=50),
            preserve_default=False,
        ),
    ]
