# Generated by Django 4.0.5 on 2024-07-10 05:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CentralApp', '0008_alter_campusavsreport_body1_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='campusavsreport',
            name='year',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
