# Generated by Django 4.0.5 on 2024-07-10 05:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CentralApp', '0009_alter_campusavsreport_year'),
    ]

    operations = [
        migrations.AlterField(
            model_name='campusavsreport',
            name='campusOrSchoolAcronym',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
