# Generated by Django 4.0.5 on 2024-07-10 21:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CentralApp', '0010_alter_campusavsreport_campusorschoolacronym'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='campusavsreport',
            name='body1',
        ),
        migrations.RemoveField(
            model_name='campusavsreport',
            name='body2',
        ),
        migrations.RemoveField(
            model_name='campusavsreport',
            name='body3',
        ),
        migrations.AddField(
            model_name='campusavsreport',
            name='TotalAttendance',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='campusavsreport',
            name='TotalAttendanceFemale',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='campusavsreport',
            name='TotalAttendanceMale',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='campusavsreport',
            name='baptism',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='campusavsreport',
            name='body',
            field=models.TextField(default='12'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='campusavsreport',
            name='healing',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='campusavsreport',
            name='salvation',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='campusavsreport',
            name='sanctification',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
