# Generated by Django 4.0.5 on 2024-07-10 21:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('CentralApp', '0011_remove_campusavsreport_body1_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='campusavsreport',
            old_name='picture5',
            new_name='picture3',
        ),
    ]
