# Generated by Django 4.0.5 on 2024-07-12 04:58

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('CentralApp', '0013_alter_campusavsreport_body_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='campusavsreport',
            name='picture1',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255),
        ),
    ]
