# Generated by Django 4.0.5 on 2024-07-12 05:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CentralApp', '0014_alter_campusavsreport_picture1'),
    ]

    operations = [
        migrations.AlterField(
            model_name='campusavsreport',
            name='picture1',
            field=models.ImageField(blank=True, upload_to='report_images/'),
        ),
    ]
