# Generated by Django 4.0.5 on 2024-07-12 05:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CentralApp', '0015_alter_campusavsreport_picture1'),
    ]

    operations = [
        migrations.AlterField(
            model_name='campusavsreport',
            name='picture1',
            field=models.FileField(blank=True, upload_to='report_images/'),
        ),
    ]
