# Generated by Django 3.2.25 on 2024-07-13 11:14

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('CentralApp', '0016_alter_campusavsreport_picture1'),
    ]

    operations = [
        migrations.AlterField(
            model_name='campusavsreport',
            name='picture1',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255),
        ),
    ]
