# Generated by Django 3.2.25 on 2024-07-13 13:36

import cloudinary_storage.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CentralApp', '0018_alter_campusavsreport_picture1'),
    ]

    operations = [
        migrations.AlterField(
            model_name='campusavsreport',
            name='picture1',
            field=models.FileField(blank=True, storage=cloudinary_storage.storage.RawMediaCloudinaryStorage(), upload_to='report_images/'),
        ),
    ]
