# Generated by Django 3.2.25 on 2024-07-13 15:04

import cloudinary_storage.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CentralApp', '0019_alter_campusavsreport_picture1'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReportImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('campusOrSchoolAcronym', models.CharField(max_length=50)),
                ('program_type', models.CharField(max_length=50)),
                ('picture1', models.FileField(storage=cloudinary_storage.storage.RawMediaCloudinaryStorage(), upload_to='report_images/')),
                ('picture2', models.FileField(storage=cloudinary_storage.storage.RawMediaCloudinaryStorage(), upload_to='report_images/')),
                ('picture3', models.FileField(storage=cloudinary_storage.storage.RawMediaCloudinaryStorage(), upload_to='report_images/')),
                ('picture4', models.FileField(storage=cloudinary_storage.storage.RawMediaCloudinaryStorage(), upload_to='report_images/')),
            ],
            options={
                'verbose_name_plural': 'CampusAVSReport',
            },
        ),
        migrations.AlterModelOptions(
            name='campusavsreport',
            options={},
        ),
        migrations.RemoveField(
            model_name='campusavsreport',
            name='picture1',
        ),
        migrations.RemoveField(
            model_name='campusavsreport',
            name='picture2',
        ),
        migrations.RemoveField(
            model_name='campusavsreport',
            name='picture3',
        ),
        migrations.RemoveField(
            model_name='campusavsreport',
            name='picture4',
        ),
    ]
