# Generated by Django 3.2.25 on 2024-07-13 15:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('CentralApp', '0020_auto_20240713_1604'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='campusavsreport',
            options={'verbose_name_plural': 'CampusAVSReportImages'},
        ),
        migrations.AlterModelOptions(
            name='reportimage',
            options={'verbose_name_plural': 'CampusAVSReportImages'},
        ),
    ]
