# Generated by Django 3.2.25 on 2024-07-13 16:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('CentralApp', '0021_auto_20240713_1605'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='campusavsreport',
            options={'verbose_name_plural': 'CampusAVSReport'},
        ),
    ]
