# Generated by Django 5.0.7 on 2024-07-15 22:45

import cloudinary_storage.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("CentralApp", "0023_historyimage_alter_campusavsreport_options_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="campusavs",
            options={"verbose_name_plural": "Campus AVS"},
        ),
        migrations.AlterField(
            model_name="campusavs",
            name="campusOrSchoolAcronym",
            field=models.CharField(max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name="historyimage",
            name="picture",
            field=models.FileField(
                storage=cloudinary_storage.storage.RawMediaCloudinaryStorage(),
                upload_to="history_images/",
            ),
        ),
    ]
