# Generated by Django 5.0.7 on 2024-07-15 22:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("CentralApp", "0024_alter_campusavs_options_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="campusavs",
            name="campusName",
            field=models.CharField(max_length=150),
        ),
    ]
