# Generated by Django 5.0.7 on 2024-07-17 20:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("CentralApp", "0025_alter_campusavs_campusname"),
    ]

    operations = [
        migrations.AddField(
            model_name="campusavs",
            name="institutionType",
            field=models.CharField(
                choices=[
                    ("university", "university"),
                    ("polytechnic", "polytechnic"),
                    ("college", "college"),
                ],
                default="university",
                max_length=50,
                verbose_name="Type of Institution",
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="campusavs",
            name="OtherScheduleOfServiceDetails",
            field=models.TextField(blank=True, verbose_name="Fellowship Venue"),
        ),
        migrations.AlterField(
            model_name="campusavs",
            name="averageNumberOfStudent",
            field=models.PositiveIntegerField(
                blank=True,
                default=0,
                null=True,
                verbose_name="Average number of Student",
            ),
        ),
        migrations.AlterField(
            model_name="campusavs",
            name="bibleStudyTime",
            field=models.CharField(
                blank=True, max_length=50, verbose_name="Bible Study Time"
            ),
        ),
        migrations.AlterField(
            model_name="campusavs",
            name="bibleStudyVenue",
            field=models.TextField(blank=True, verbose_name="Bible Study Venue"),
        ),
        migrations.AlterField(
            model_name="campusavs",
            name="campusName",
            field=models.CharField(max_length=150, verbose_name="Campus Full name"),
        ),
        migrations.AlterField(
            model_name="campusavs",
            name="campusOrSchoolAcronym",
            field=models.CharField(
                max_length=50, unique=True, verbose_name="Campus or institution Acronym"
            ),
        ),
        migrations.AlterField(
            model_name="campusavs",
            name="coordinator_course",
            field=models.CharField(
                blank=True, max_length=800, null=True, verbose_name="Coordinator Course"
            ),
        ),
        migrations.AlterField(
            model_name="campusavs",
            name="coordinator_email",
            field=models.EmailField(
                blank=True, max_length=254, null=True, verbose_name="Coordinator email"
            ),
        ),
        migrations.AlterField(
            model_name="campusavs",
            name="coordinator_level",
            field=models.CharField(
                blank=True,
                max_length=50,
                null=True,
                verbose_name="Coordinator Level Or program",
            ),
        ),
        migrations.AlterField(
            model_name="campusavs",
            name="coordinator_name",
            field=models.CharField(
                blank=True, max_length=300, null=True, verbose_name="Coordinator name"
            ),
        ),
        migrations.AlterField(
            model_name="campusavs",
            name="coordinator_phonenumber",
            field=models.CharField(
                blank=True,
                max_length=50,
                null=True,
                verbose_name="Coordinator Phone number",
            ),
        ),
        migrations.AlterField(
            model_name="campusavs",
            name="coordinator_picture",
            field=models.ImageField(
                blank=True,
                upload_to="campus_avs_images_cord/",
                verbose_name="Upload Coordinator picture",
            ),
        ),
        migrations.AlterField(
            model_name="campusavs",
            name="fellowshipTime",
            field=models.CharField(
                blank=True, max_length=50, verbose_name="Fellowship Time"
            ),
        ),
        migrations.AlterField(
            model_name="campusavs",
            name="joinAlumiGroup",
            field=models.URLField(
                blank=True, null=True, verbose_name="Link to join Alumni Group"
            ),
        ),
        migrations.AlterField(
            model_name="campusavs",
            name="numberOfWorkforce",
            field=models.PositiveIntegerField(
                blank=True,
                default=0,
                null=True,
                verbose_name="Total number of workforce",
            ),
        ),
        migrations.AlterField(
            model_name="campusavs",
            name="secretary_course",
            field=models.CharField(
                blank=True, max_length=800, null=True, verbose_name="Secretary course"
            ),
        ),
        migrations.AlterField(
            model_name="campusavs",
            name="secretary_email",
            field=models.EmailField(
                blank=True, max_length=254, null=True, verbose_name="Secretary email"
            ),
        ),
        migrations.AlterField(
            model_name="campusavs",
            name="secretary_level",
            field=models.CharField(
                blank=True,
                max_length=50,
                null=True,
                verbose_name="Secretary Level or program",
            ),
        ),
        migrations.AlterField(
            model_name="campusavs",
            name="secretary_name",
            field=models.CharField(
                blank=True, max_length=300, null=True, verbose_name="Secretary name"
            ),
        ),
        migrations.AlterField(
            model_name="campusavs",
            name="secretary_phonenumber",
            field=models.CharField(
                blank=True,
                max_length=50,
                null=True,
                verbose_name="Secretary Phone number",
            ),
        ),
        migrations.AlterField(
            model_name="campusavs",
            name="secretary_picture",
            field=models.ImageField(
                blank=True,
                upload_to="campus_avs_images_sect/",
                verbose_name="Upload Secretary Picture",
            ),
        ),
        migrations.AlterField(
            model_name="campusavsreport",
            name="program_type",
            field=models.CharField(
                choices=[
                    ("revival_program", "National Revival Program (NRP)"),
                    ("welcome_program", "Fresher's Welcome Program"),
                ],
                max_length=50,
            ),
        ),
        migrations.AlterField(
            model_name="reportimage",
            name="program_type",
            field=models.CharField(
                choices=[
                    ("revival_program", "National Revival Program (NRP)"),
                    ("welcome_program", "Fresher's Welcome Program"),
                ],
                max_length=50,
            ),
        ),
    ]
