# Generated by Django 5.0.7 on 2024-07-22 08:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("CentralApp", "0026_campusavs_institutiontype_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="campusavs",
            name="fellowship_email",
            field=models.CharField(
                blank=True,
                max_length=50,
                verbose_name="Campus Fellowship Email Address",
            ),
        ),
        migrations.AddField(
            model_name="campusavs",
            name="fellowship_facebook_link",
            field=models.URLField(
                blank=True, null=True, verbose_name="Fellowship Facebook link"
            ),
        ),
        migrations.AddField(
            model_name="campusavs",
            name="fellowship_instagram_link",
            field=models.URLField(
                blank=True, null=True, verbose_name="Fellowship Instagram Link"
            ),
        ),
        migrations.AddField(
            model_name="campusavs",
            name="fellowship_phone_number",
            field=models.CharField(
                blank=True, max_length=50, verbose_name="Campus Fellowship Phone number"
            ),
        ),
    ]
