# Generated by Django 5.0.7 on 2024-07-22 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("CentralApp", "0027_campusavs_fellowship_email_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="campusavs",
            name="OtherScheduleOfServiceDetails",
            field=models.TextField(
                blank=True, verbose_name="Other Fellowship Service Details"
            ),
        ),
        migrations.AlterField(
            model_name="campusavs",
            name="fellowshipVenue",
            field=models.TextField(blank=True, verbose_name="Fellowship Venue"),
        ),
    ]
