# Generated by Django 5.0.7 on 2024-07-26 22:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("CentralApp", "0029_campusavs_active_inactive"),
    ]

    operations = [
        migrations.CreateModel(
            name="WebPageIndexData",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "event_name",
                    models.CharField(
                        max_length=50, unique=True, verbose_name="Event Name"
                    ),
                ),
                (
                    "event_Live_link",
                    models.URLField(
                        blank=True, null=True, verbose_name="Event Live link"
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Latest Event",
            },
        ),
    ]
