# Generated by Django 5.0.7 on 2024-07-26 22:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("CentralApp", "0030_webpageindexdata"),
    ]

    operations = [
        migrations.AddField(
            model_name="campusavsreport",
            name="google_drive_link",
            field=models.URLField(
                blank=True, null=True, verbose_name="Google Drive link to reports"
            ),
        ),
    ]
