# Generated by Django 5.0.7 on 2024-07-27 07:38

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("CentralApp", "0031_campusavsreport_google_drive_link"),
    ]

    operations = [
        migrations.AddField(
            model_name="webpageindexdata",
            name="posted",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
    ]
