# Generated by Django 5.0.7 on 2024-08-03 09:06

import cloudinary_storage.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("CentralApp", "0032_webpageindexdata_posted"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="campusavs",
            options={"verbose_name_plural": "List of Campus AVS"},
        ),
        migrations.RemoveField(
            model_name="campusavs",
            name="fellowship_phone_number",
        ),
        migrations.AddField(
            model_name="campusavs",
            name="bibleStudyDay",
            field=models.CharField(
                blank=True, max_length=50, verbose_name="Day of the Week"
            ),
        ),
        migrations.AddField(
            model_name="campusavs",
            name="fellowshipDay",
            field=models.CharField(
                blank=True, max_length=50, verbose_name="Day of the Week"
            ),
        ),
        migrations.AddField(
            model_name="campusavs",
            name="nrp_TotalAttendanceFemale",
            field=models.PositiveIntegerField(
                blank=True,
                default=1,
                null=True,
                verbose_name="Number of Male in attendance",
            ),
        ),
        migrations.AddField(
            model_name="campusavs",
            name="nrp_TotalAttendanceMale",
            field=models.PositiveIntegerField(
                blank=True,
                default=1,
                null=True,
                verbose_name="Number of Male in attendance",
            ),
        ),
        migrations.AddField(
            model_name="campusavs",
            name="nrp_baptism",
            field=models.PositiveIntegerField(
                blank=True,
                default=1,
                null=True,
                verbose_name="Number of People Baptism",
            ),
        ),
        migrations.AddField(
            model_name="campusavs",
            name="nrp_body",
            field=models.TextField(
                blank=True, null=True, verbose_name="Number of People Saved"
            ),
        ),
        migrations.AddField(
            model_name="campusavs",
            name="nrp_google_drive_link",
            field=models.URLField(
                blank=True, null=True, verbose_name="Google Drive link to reports"
            ),
        ),
        migrations.AddField(
            model_name="campusavs",
            name="nrp_healing",
            field=models.PositiveIntegerField(
                blank=True, default=1, null=True, verbose_name="Number of People Healed"
            ),
        ),
        migrations.AddField(
            model_name="campusavs",
            name="nrp_picture1",
            field=models.FileField(
                default=False,
                storage=cloudinary_storage.storage.RawMediaCloudinaryStorage(),
                upload_to="report_images/",
                verbose_name="Picture (1)",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="campusavs",
            name="nrp_picture2",
            field=models.FileField(
                default=False,
                storage=cloudinary_storage.storage.RawMediaCloudinaryStorage(),
                upload_to="report_images/",
                verbose_name="Picture (2)",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="campusavs",
            name="nrp_picture3",
            field=models.FileField(
                default=False,
                storage=cloudinary_storage.storage.RawMediaCloudinaryStorage(),
                upload_to="report_images/",
                verbose_name="Picture (3)",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="campusavs",
            name="nrp_picture4",
            field=models.FileField(
                default=False,
                storage=cloudinary_storage.storage.RawMediaCloudinaryStorage(),
                upload_to="report_images/",
                verbose_name="Picture (4)",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="campusavs",
            name="nrp_picture5",
            field=models.FileField(
                default=False,
                storage=cloudinary_storage.storage.RawMediaCloudinaryStorage(),
                upload_to="report_images/",
                verbose_name="Picture (5)",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="campusavs",
            name="nrp_picture6",
            field=models.FileField(
                default=False,
                storage=cloudinary_storage.storage.RawMediaCloudinaryStorage(),
                upload_to="report_images/",
                verbose_name="Picture (6)",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="campusavs",
            name="nrp_picture7",
            field=models.FileField(
                default=False,
                storage=cloudinary_storage.storage.RawMediaCloudinaryStorage(),
                upload_to="report_images/",
                verbose_name="Picture (7)",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="campusavs",
            name="nrp_picture8",
            field=models.FileField(
                default=False,
                storage=cloudinary_storage.storage.RawMediaCloudinaryStorage(),
                upload_to="report_images/",
                verbose_name="Picture (8)",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="campusavs",
            name="nrp_salvation",
            field=models.PositiveIntegerField(
                blank=True, default=1, null=True, verbose_name="Number of People Saved"
            ),
        ),
        migrations.AddField(
            model_name="campusavs",
            name="nrp_sanctification",
            field=models.PositiveIntegerField(
                blank=True,
                default=1,
                null=True,
                verbose_name="Number of People Sanctified",
            ),
        ),
        migrations.AddField(
            model_name="campusavs",
            name="wlc_TotalAttendanceFemale",
            field=models.PositiveIntegerField(
                blank=True, default=1, verbose_name="Number of Male in attendance"
            ),
        ),
        migrations.AddField(
            model_name="campusavs",
            name="wlc_TotalAttendanceMale",
            field=models.PositiveIntegerField(
                blank=True, default=1, verbose_name="Number of Male in attendance"
            ),
        ),
        migrations.AddField(
            model_name="campusavs",
            name="wlc_baptism",
            field=models.PositiveIntegerField(
                blank=True, default=1, verbose_name="Number of People Baptism"
            ),
        ),
        migrations.AddField(
            model_name="campusavs",
            name="wlc_body",
            field=models.TextField(
                blank=True, null=True, verbose_name="Number of People Saved"
            ),
        ),
        migrations.AddField(
            model_name="campusavs",
            name="wlc_google_drive_link",
            field=models.URLField(
                blank=True, null=True, verbose_name="Google Drive link to reports"
            ),
        ),
        migrations.AddField(
            model_name="campusavs",
            name="wlc_healing",
            field=models.PositiveIntegerField(
                blank=True, default=1, verbose_name="Number of People Healing"
            ),
        ),
        migrations.AddField(
            model_name="campusavs",
            name="wlc_picture1",
            field=models.FileField(
                default=False,
                storage=cloudinary_storage.storage.RawMediaCloudinaryStorage(),
                upload_to="report_images/",
                verbose_name="Picture (1)",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="campusavs",
            name="wlc_picture2",
            field=models.FileField(
                default=False,
                storage=cloudinary_storage.storage.RawMediaCloudinaryStorage(),
                upload_to="report_images/",
                verbose_name="Picture (2)",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="campusavs",
            name="wlc_picture3",
            field=models.FileField(
                default=False,
                storage=cloudinary_storage.storage.RawMediaCloudinaryStorage(),
                upload_to="report_images/",
                verbose_name="Picture (3)",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="campusavs",
            name="wlc_picture4",
            field=models.FileField(
                default=False,
                storage=cloudinary_storage.storage.RawMediaCloudinaryStorage(),
                upload_to="report_images/",
                verbose_name="Picture (4)",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="campusavs",
            name="wlc_picture5",
            field=models.FileField(
                default=False,
                storage=cloudinary_storage.storage.RawMediaCloudinaryStorage(),
                upload_to="report_images/",
                verbose_name="Picture (5)",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="campusavs",
            name="wlc_picture6",
            field=models.FileField(
                default=False,
                storage=cloudinary_storage.storage.RawMediaCloudinaryStorage(),
                upload_to="report_images/",
                verbose_name="Picture (6)",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="campusavs",
            name="wlc_picture7",
            field=models.FileField(
                default=False,
                storage=cloudinary_storage.storage.RawMediaCloudinaryStorage(),
                upload_to="report_images/",
                verbose_name="Picture (7)",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="campusavs",
            name="wlc_picture8",
            field=models.FileField(
                default=False,
                storage=cloudinary_storage.storage.RawMediaCloudinaryStorage(),
                upload_to="report_images/",
                verbose_name="Picture (8)",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="campusavs",
            name="wlc_salvation",
            field=models.PositiveIntegerField(
                blank=True, default=1, verbose_name="Number of People Saved"
            ),
        ),
        migrations.AddField(
            model_name="campusavs",
            name="wlc_sanctification",
            field=models.PositiveIntegerField(
                blank=True, default=1, verbose_name="Number of People Sanctified"
            ),
        ),
        migrations.AlterField(
            model_name="campusavs",
            name="about",
            field=models.TextField(verbose_name="About, Remarks or Report"),
        ),
        migrations.AlterField(
            model_name="campusavs",
            name="bibleStudyTime",
            field=models.CharField(blank=True, max_length=50, verbose_name="Time"),
        ),
        migrations.AlterField(
            model_name="campusavs",
            name="bibleStudyVenue",
            field=models.CharField(blank=True, max_length=400, verbose_name="Venue"),
        ),
        migrations.AlterField(
            model_name="campusavs",
            name="campusOrSchoolAcronym",
            field=models.CharField(
                help_text="Acronym like FUTA or UNILAG",
                max_length=50,
                unique=True,
                verbose_name="School Acronym",
            ),
        ),
        migrations.AlterField(
            model_name="campusavs",
            name="coordinator_picture",
            field=models.ImageField(
                blank=True,
                upload_to="campus_avs_images_cord/",
                verbose_name="Upload Coordinator picture (Headshot only)",
            ),
        ),
        migrations.AlterField(
            model_name="campusavs",
            name="fellowshipTime",
            field=models.CharField(blank=True, max_length=50, verbose_name="Time"),
        ),
        migrations.AlterField(
            model_name="campusavs",
            name="fellowshipVenue",
            field=models.CharField(blank=True, max_length=400, verbose_name="Venue"),
        ),
        migrations.AlterField(
            model_name="campusavs",
            name="flyer",
            field=models.ImageField(
                blank=True,
                help_text="A Landscape Picture: Group Photograph of AFCF or During a service",
                upload_to="campus_avs_images/",
                verbose_name="AFCF Picture",
            ),
        ),
        migrations.AlterField(
            model_name="campusavs",
            name="institutionType",
            field=models.CharField(
                choices=[
                    ("university", "University"),
                    ("college", "College of Education/Medcine or Technology"),
                    ("polytechnic", "Polytechnic"),
                ],
                max_length=50,
                verbose_name="Type of Institution",
            ),
        ),
        migrations.AlterField(
            model_name="campusavs",
            name="secretary_picture",
            field=models.ImageField(
                blank=True,
                upload_to="campus_avs_images_sect/",
                verbose_name="Upload Secretary Picture  (Headshot only)",
            ),
        ),
    ]
