# Generated by Django 5.0.7 on 2024-08-05 19:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("CentralApp", "0033_alter_campusavs_options_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="campusavs",
            name="flyer2",
            field=models.ImageField(
                blank=True,
                help_text="Upload ANOTHER Group Photograph of AFCF or Picture taken during a service",
                upload_to="campus_avs_images/",
                verbose_name="AFCF Picture2",
            ),
        ),
        migrations.AlterField(
            model_name="campusavs",
            name="flyer",
            field=models.ImageField(
                blank=True,
                help_text="Upload A Group Photograph of AFCF or Picture taken during a service.",
                upload_to="campus_avs_images/",
                verbose_name="AFCF Picture",
            ),
        ),
        migrations.AlterField(
            model_name="campusavs",
            name="nrp_TotalAttendanceFemale",
            field=models.PositiveIntegerField(
                blank=True,
                default=1,
                null=True,
                verbose_name="Number of Female in attendance",
            ),
        ),
        migrations.AlterField(
            model_name="campusavs",
            name="nrp_baptism",
            field=models.PositiveIntegerField(
                blank=True,
                default=1,
                null=True,
                verbose_name="Number of People Baptised",
            ),
        ),
        migrations.AlterField(
            model_name="campusavs",
            name="nrp_body",
            field=models.TextField(blank=True, null=True, verbose_name="Note"),
        ),
        migrations.AlterField(
            model_name="campusavs",
            name="wlc_TotalAttendanceFemale",
            field=models.PositiveIntegerField(
                blank=True, default=1, verbose_name="Number of Female in attendance"
            ),
        ),
        migrations.AlterField(
            model_name="campusavs",
            name="wlc_baptism",
            field=models.PositiveIntegerField(
                blank=True, default=1, verbose_name="Number of People Baptised"
            ),
        ),
        migrations.AlterField(
            model_name="campusavs",
            name="wlc_body",
            field=models.TextField(blank=True, null=True, verbose_name="Note"),
        ),
    ]
