# Generated by Django 5.0.7 on 2024-08-14 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("CentralApp", "0036_alter_campusavs_nrp_year_alter_campusavs_wlc_year"),
    ]

    operations = [
        migrations.AddField(
            model_name="campusavs",
            name="nrp_TotalAttendance",
            field=models.PositiveIntegerField(
                blank=True,
                default=1,
                verbose_name="Total Number of people in attendance",
            ),
        ),
        migrations.AddField(
            model_name="campusavs",
            name="wlc_TotalAttendance",
            field=models.PositiveIntegerField(
                blank=True,
                default=1,
                verbose_name="Total Number of people in attendance",
            ),
        ),
    ]
