# Generated by Django 5.0.7 on 2024-08-16 22:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("CentralApp", "0039_alter_campusavs_about"),
    ]

    operations = [
        migrations.AddField(
            model_name="campusavs",
            name="nrp_TotalOfficiatingMemeber",
            field=models.PositiveIntegerField(
                blank=True,
                default=0,
                null=True,
                verbose_name="Number of Officiating Members",
            ),
        ),
        migrations.AddField(
            model_name="campusavs",
            name="nrp_other_blessing",
            field=models.PositiveIntegerField(
                blank=True,
                default=0,
                null=True,
                verbose_name="Number of Other Blessing",
            ),
        ),
        migrations.AddField(
            model_name="campusavs",
            name="nrp_reannointing",
            field=models.PositiveIntegerField(
                blank=True,
                default=0,
                null=True,
                verbose_name="Number of People Reannointed",
            ),
        ),
        migrations.AddField(
            model_name="campusavs",
            name="wlc_TotalOfficiatingMemeber",
            field=models.PositiveIntegerField(
                blank=True,
                default=0,
                null=True,
                verbose_name="Number of Officiating Members",
            ),
        ),
        migrations.AddField(
            model_name="campusavs",
            name="wlc_other_blessing",
            field=models.PositiveIntegerField(
                blank=True,
                default=0,
                null=True,
                verbose_name="Number of Other Blessing",
            ),
        ),
        migrations.AddField(
            model_name="campusavs",
            name="wlc_reannointing",
            field=models.PositiveIntegerField(
                blank=True,
                default=0,
                null=True,
                verbose_name="Number of People Reannointed",
            ),
        ),
        migrations.AlterField(
            model_name="campusavs",
            name="nrp_TotalAttendance",
            field=models.PositiveIntegerField(
                blank=True,
                default=0,
                verbose_name="Total Number of people in attendance",
            ),
        ),
        migrations.AlterField(
            model_name="campusavs",
            name="nrp_TotalAttendanceFemale",
            field=models.PositiveIntegerField(
                blank=True,
                default=0,
                null=True,
                verbose_name="Number of Female in attendance",
            ),
        ),
        migrations.AlterField(
            model_name="campusavs",
            name="nrp_TotalAttendanceMale",
            field=models.PositiveIntegerField(
                blank=True,
                default=0,
                null=True,
                verbose_name="Number of Male in attendance",
            ),
        ),
        migrations.AlterField(
            model_name="campusavs",
            name="nrp_baptism",
            field=models.PositiveIntegerField(
                blank=True,
                default=0,
                null=True,
                verbose_name="Number of People Baptised",
            ),
        ),
        migrations.AlterField(
            model_name="campusavs",
            name="nrp_healing",
            field=models.PositiveIntegerField(
                blank=True, default=0, null=True, verbose_name="Number of People Healed"
            ),
        ),
        migrations.AlterField(
            model_name="campusavs",
            name="nrp_salvation",
            field=models.PositiveIntegerField(
                blank=True, default=0, null=True, verbose_name="Number of People Saved"
            ),
        ),
        migrations.AlterField(
            model_name="campusavs",
            name="nrp_sanctification",
            field=models.PositiveIntegerField(
                blank=True,
                default=0,
                null=True,
                verbose_name="Number of People Sanctified",
            ),
        ),
        migrations.AlterField(
            model_name="campusavs",
            name="wlc_TotalAttendance",
            field=models.PositiveIntegerField(
                blank=True,
                default=0,
                verbose_name="Total Number of people in attendance",
            ),
        ),
        migrations.AlterField(
            model_name="campusavs",
            name="wlc_TotalAttendanceFemale",
            field=models.PositiveIntegerField(
                blank=True, default=0, verbose_name="Number of Female in attendance"
            ),
        ),
        migrations.AlterField(
            model_name="campusavs",
            name="wlc_TotalAttendanceMale",
            field=models.PositiveIntegerField(
                blank=True, default=0, verbose_name="Number of Male in attendance"
            ),
        ),
        migrations.AlterField(
            model_name="campusavs",
            name="wlc_baptism",
            field=models.PositiveIntegerField(
                blank=True, default=0, verbose_name="Number of People Baptised"
            ),
        ),
        migrations.AlterField(
            model_name="campusavs",
            name="wlc_healing",
            field=models.PositiveIntegerField(
                blank=True, default=0, verbose_name="Number of People Healed"
            ),
        ),
        migrations.AlterField(
            model_name="campusavs",
            name="wlc_salvation",
            field=models.PositiveIntegerField(
                blank=True, default=0, verbose_name="Number of People Saved"
            ),
        ),
        migrations.AlterField(
            model_name="campusavs",
            name="wlc_sanctification",
            field=models.PositiveIntegerField(
                blank=True, default=0, verbose_name="Number of People Sanctified"
            ),
        ),
    ]
