# Generated by Django 5.0.7 on 2024-09-30 07:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("CentralApp", "0040_campusavs_nrp_totalofficiatingmemeber_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="campusavs",
            name="UpdateAboutSchool",
            field=models.TextField(
                blank=True,
                help_text="What's going on in your Campus Fellowhship that you'll want others to know about",
                verbose_name="AFCF Campus Update",
            ),
        ),
    ]
